from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path
from string import Template
from typing import Any

import filter as fast_filter


VALIDATION_TEMPLATE = Template(
    """# Auto-generated by export_perf_validation.py
# problem_id: $problem_id
# sample_id: $sample_id
# selected_speedup: $selected_speedup x

import asyncio
import os
from uuid import uuid4

import httpx

DEFAULT_SERVER_URLS = (
    os.getenv("KERNELGYM_SERVER_URL"),
    "http://172.18.0.3:8001",
    "http://192.168.31.68:8001",
    "http://localhost:10907",
)


async def resolve_server_url() -> str:
    probe_timeout = httpx.Timeout(5.0, connect=1.0)
    async with httpx.AsyncClient(timeout=probe_timeout) as client:
        for base_url in DEFAULT_SERVER_URLS:
            if not base_url:
                continue
            try:
                response = await client.get(f"{base_url}/health")
                response.raise_for_status()
                return base_url
            except httpx.HTTPError:
                continue

    raise RuntimeError(
        "Could not connect to a KernelGYM server. "
        "Set KERNELGYM_SERVER_URL to a reachable base URL."
    )


async def evaluate_kernelbench():
    server_url = await resolve_server_url()
    task_id = f"$task_prefix-kernel-{uuid4().hex[:8]}"
    reference_code = $reference_code

    kernel_code = $kernel_code

    timeout = httpx.Timeout(300.0, connect=10.0)
    async with httpx.AsyncClient(timeout=timeout) as client:
        response = await client.post(
            f"{server_url}/evaluate",
            json={
                "task_id": task_id,
                "reference_code": reference_code,
                "kernel_code": kernel_code,
                "entry_point": "Model",
                "backend": "triton",
                "reference_backend": "torch_compile",
                "num_correct_trials": 5,
                "num_perf_trials": 100,
                "force_refresh": True,
            },
        )
        response.raise_for_status()
        return response.json()


result = asyncio.run(evaluate_kernelbench())
print(f"Compiled: {result['compiled']}")
print(f"Correctness: {result['correctness']}")
print(f"Speedup: {result['speedup']:.2f}x")
print(f"Reference Runtime: {result['reference_runtime']:.4f} ms")
print(f"Kernel Runtime: {result['kernel_runtime']:.4f} ms")
"""
)


def get_default_run_path() -> str:
    env_path = os.getenv("KERNELGYM_RUN_PATH", "").strip()
    if env_path:
        return env_path

    script_root = Path(__file__).resolve().parent
    candidates = [
        script_root,
        script_root / "grading_results",
        Path.cwd(),
    ]

    for path in candidates:
        if path.exists():
            return str(path)
    return str(candidates[0])


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate one KernelGYM performance validation file per filtered problem, "
            "using the best-speedup kernel and the matching reference.py."
        )
    )
    parser.add_argument(
        "--run-path",
        type=str,
        default=get_default_run_path(),
        help="Run root path or grading_results path.",
    )
    parser.add_argument(
        "--conversations",
        type=Path,
        default=None,
        help="Optional override for graded_results_conversations_conversations.jsonl.",
    )
    parser.add_argument(
        "--metrics",
        type=Path,
        default=None,
        help="Optional override for metrics.json.",
    )
    parser.add_argument(
        "--eval-outputs",
        type=Path,
        default=None,
        help="Optional override for eval_outputs directory.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Directory to store generated validation scripts.",
    )
    parser.add_argument(
        "--metric-prefix",
        type=str,
        default="best_by_turn",
        help="Metric prefix to use: best_by_turn, best_by_turn_<N>, turn, or turn_<N>.",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=fast_filter.DEFAULT_THRESHOLD,
        help="Speedup threshold used when selecting filtered kernels.",
    )
    parser.add_argument(
        "--max-turn",
        type=int,
        default=None,
        help="Optional max turn for best_by_turn selection.",
    )
    return parser.parse_args()


def resolve_grading_results_path(user_input_path: str) -> Path:
    root = Path(user_input_path).expanduser()
    if not root.exists():
        raise FileNotFoundError(f"Path does not exist: {root}")

    if root.name == "grading_results":
        grading_results_dir = root
    elif (root / "grading_results").exists():
        grading_results_dir = root / "grading_results"
    else:
        raise FileNotFoundError(
            "Cannot locate grading_results. Please provide either run root or grading_results path."
        )

    return grading_results_dir


def resolve_input_paths(args: argparse.Namespace) -> tuple[Path, Path, Path]:
    if args.conversations and args.metrics and args.eval_outputs:
        return args.conversations, args.metrics, args.eval_outputs

    grading_results_dir = resolve_grading_results_path(args.run_path)
    conversations_path = args.conversations or (
        grading_results_dir / "graded_results_conversations_conversations.jsonl"
    )
    metrics_path = args.metrics or (grading_results_dir / "metrics.json")
    eval_outputs_path = args.eval_outputs or (grading_results_dir / "eval_outputs")

    if not conversations_path.exists():
        raise FileNotFoundError(f"Conversations file not found: {conversations_path}")
    if not metrics_path.exists():
        raise FileNotFoundError(f"metrics.json not found: {metrics_path}")
    if not eval_outputs_path.exists():
        raise FileNotFoundError(f"eval_outputs not found: {eval_outputs_path}")

    return conversations_path, metrics_path, eval_outputs_path


def sanitize_token(text: Any) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", str(text)).strip("_.") or "unknown"


def build_task_prefix(problem_id: Any) -> str:
    token = sanitize_token(problem_id)
    if token.isdigit():
        return f"p{token}"
    return f"problem_{token}"


def build_output_dir(
    output_dir_arg: Path | None,
    metric_scope: str,
    target_turn: int,
    threshold: float,
) -> Path:
    if output_dir_arg is not None:
        return output_dir_arg
    output_stem = fast_filter.build_output_stem(metric_scope, target_turn, threshold)
    return Path(__file__).resolve().parent / f"{output_stem}_perf_validation"


def load_reference_code(selected_sample: dict[str, Any]) -> str:
    source_eval_output_dir = selected_sample.get("source_eval_output_dir")
    if not source_eval_output_dir:
        return ""

    reference_path = Path(str(source_eval_output_dir)) / "reference.py"
    if not reference_path.exists():
        return ""

    return reference_path.read_text(encoding="utf-8", errors="replace")


def render_validation_script(
    problem_id: Any,
    sample_id: Any,
    speedup: float,
    reference_code: str,
    kernel_code: str,
) -> str:
    return VALIDATION_TEMPLATE.substitute(
        problem_id=str(problem_id),
        sample_id="" if sample_id is None else str(sample_id),
        selected_speedup=f"{float(speedup):.4f}",
        task_prefix=build_task_prefix(problem_id),
        reference_code=json.dumps(reference_code, ensure_ascii=False),
        kernel_code=json.dumps(kernel_code, ensure_ascii=False),
    )


def main() -> int:
    args = parse_args()
    conversations_path, metrics_path, eval_outputs_path = resolve_input_paths(args)

    filter_result = fast_filter.collect_filtered_samples(
        conversations_path=conversations_path,
        metrics_path=metrics_path,
        eval_outputs_path=eval_outputs_path,
        metric_prefix=args.metric_prefix,
        threshold=float(args.threshold),
        requested_max_turn=args.max_turn,
    )

    output_dir = build_output_dir(
        output_dir_arg=args.output_dir,
        metric_scope=str(filter_result["metric_scope"]),
        target_turn=int(filter_result["target_turn"]),
        threshold=float(filter_result["threshold"]),
    )
    output_dir.mkdir(parents=True, exist_ok=True)

    generated_files: list[dict[str, Any]] = []
    skipped_files: list[dict[str, Any]] = []

    for selected_sample in filter_result["samples"]:
        problem_id = selected_sample.get("problem_id")
        sample_id = selected_sample.get("sample_id")
        speedup = float(selected_sample.get("qualified_turn_performance", 0.0))
        reference_code = load_reference_code(selected_sample)
        kernel_code = str(selected_sample.get("selected_kernel", "")).strip()

        if not reference_code.strip() or not kernel_code:
            skipped_files.append(
                {
                    "problem_id": problem_id,
                    "sample_id": sample_id,
                    "reason": "missing reference.py or selected kernel code",
                    "source_eval_output_dir": selected_sample.get("source_eval_output_dir"),
                }
            )
            continue

        file_name = f"problem_{sanitize_token(problem_id)}_perf_validate.py"
        output_path = output_dir / file_name
        script_text = render_validation_script(
            problem_id=problem_id,
            sample_id=sample_id,
            speedup=speedup,
            reference_code=reference_code,
            kernel_code=kernel_code,
        )
        output_path.write_text(script_text, encoding="utf-8")

        generated_files.append(
            {
                "problem_id": problem_id,
                "sample_id": sample_id,
                "qualified_turn_id": selected_sample.get("qualified_turn_id"),
                "qualified_turn_performance": speedup,
                "source_eval_output_name": selected_sample.get("source_eval_output_name"),
                "source_eval_output_dir": selected_sample.get("source_eval_output_dir"),
                "output_path": str(output_path),
            }
        )

    manifest = {
        "metric_name": filter_result.get("metric_name"),
        "metric_scope": filter_result.get("metric_scope"),
        "metric_prefix": filter_result.get("metric_prefix"),
        "threshold": filter_result.get("threshold"),
        "target_turn": filter_result.get("target_turn"),
        "selected_problems": filter_result.get("selected_problems"),
        "generated_count": len(generated_files),
        "skipped_count": len(skipped_files),
        "output_dir": str(output_dir),
        "generated_files": generated_files,
        "skipped_files": skipped_files,
    }

    manifest_path = output_dir / "perf_validation_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    print(json.dumps(manifest, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())